[client]
port=3306

[mysqld]
port=3306
basedir=C:/Program Files/MySQL/MySQL Server 8.0
datadir=D:/VS/Cafeteria-Management/.mysql/data
default-storage-engine=INNODB
sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
log-error=D:/VS/Cafeteria-Management/.mysql/mysql-error.log
general-log=0
slow-query-log=0
max_connections=151
innodb_buffer_pool_size=128M
innodb_redo_log_capacity=100M
lower_case_table_names=1
secure-file-priv=D:/VS/Cafeteria-Management/.mysql/uploads
default_authentication_plugin=mysql_native_password
authentication_policy=*,,
